# Generated by Django 2.1.1 on 2018-10-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(0, 'Incomplete'), (1, 'Complete')], max_length=10)),
                ('created', models.DateTimeField(verbose_name='Created Datetime')),
                ('updated', models.DateTimeField(verbose_name='Updated Datetime')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
            ],
        ),
    ]
