# Generated by Django 2.1.1 on 2018-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete')], max_length=10),
        ),
    ]
