# Generated by Django 2.1.1 on 2018-10-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181013_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete')]),
        ),
    ]
