# Generated by Django 2.1.1 on 2018-10-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181013_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updated',
            field=models.DateTimeField(null=True, verbose_name='Updated'),
        ),
    ]
