# Generated by Django 2.1.1 on 2018-10-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20181018_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_item', models.CharField(max_length=255)),
                ('sub_status', models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete')], default=0)),
                ('sub_created', models.DateTimeField(verbose_name='Created')),
                ('sub_updated', models.DateTimeField(null=True, verbose_name='Updated')),
                ('sub_deadline', models.DateTimeField(null=True, verbose_name='Deadline')),
                ('sub_description', models.CharField(max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='starred',
            field=models.IntegerField(choices=[(0, 'Unstarred'), (1, 'Starred')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Incomplete'), (1, 'Complete')], default=0),
        ),
        migrations.AddField(
            model_name='subitem',
            name='todo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.TodoItem'),
        ),
    ]
