# Generated by Django 2.1.1 on 2018-10-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20181021_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='sub_status',
            new_name='status',
        ),
    ]
