# Generated by Django 2.1.2 on 2018-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20181022_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='sub_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='sub_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='sub_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='starred',
            field=models.IntegerField(blank=True, choices=[(0, 'Unstarred'), (1, 'Starred')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
    ]
