language: python

python:
  - 3.6.2


install:
  - pip install -r requirements.txt

before_script:
- cd todoapp
- echo -e "SECRET_KEY = 'secret_key'" >> todoapp/secrets.py

script:
  - python manage.py test
